import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { deserializeProject } from "@/io/project/ProjectFile";
import { isSymbol, type Project, type SymbolItem } from "@/core/doc/types";
import type { NodeId } from "@/core/doc/ids";
import { fakeAssets } from "./realProject";

/**
 * The bone + IK rig: a stick figure on four two-bone chains, with a
 * front-view `dance` and a side-view `run`.
 *
 * Generated by `npx vite-node scripts/buildStickman.ts` — regenerate it rather
 * than editing the file.
 */
export const STICKMAN_PATH = fileURLToPath(
  new URL("./projects/stickman.animo", import.meta.url),
);

export interface Stickman {
  project: Project;
  rig: SymbolItem;
  diagnostics: { message: string }[];
  /** The node with that name, or a throw — a typo must not read as "absent". */
  node(name: string): NodeId;
}

export async function loadStickman(): Promise<Stickman> {
  const bytes = readFileSync(STICKMAN_PATH);
  const buffer = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength);
  const { project, diagnostics } = await deserializeProject(buffer as ArrayBuffer, fakeAssets());

  const rig = project.items[project.rootSymbolId];
  if (!isSymbol(rig)) throw new Error("the stickman root is not a symbol");

  return {
    project,
    rig,
    diagnostics,
    node(name: string): NodeId {
      const found = Object.values(rig.nodes).find((n) => n.name === name);
      if (!found) throw new Error(`no node named ${name} in the stickman rig`);
      return found.id;
    },
  };
}
